server:
  port: ${SERVER_PORT:8888}
spring:
  application:
    name: jgateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/jeureka