server:
  port: ${SERVER_PORT:8765}
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#  security:
#    oauth2:
#      client:
#        registration:
#          jgateway:
#            provider: spring
#            client-id: jgateway
#            client-secret: secret
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            scope: openid,resource.read
#        provider:
#          spring:
#            issuer-uri: http://localhost:8083
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/j-eureka